    -- =====================================================================
    -- SCRIPT DE CRIACAO - BANCO DE DADOS ORACLE
    -- PROJETO: SkillMatch AI
    -- =====================================================================

    -- Garante que o script pare em caso de erro
    WHENEVER SQLERROR EXIT SQL.SQLCODE;

    -- === 0. LIMPEZA (Para testes, se as tabelas já existirem) ===
    BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_SKILL_USUARIO_HABILIDADE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_SKILL_VAGA_HABILIDADE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_SKILL_HABILIDADE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_SKILL_USUARIO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_SKILL_VAGA CASCADE CONSTRAINTS';
    EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
    END;
    /

    -- === 1. CRIACAO DAS TABELAS ===

    -- Tabela principal de Habilidades (Hard Skills, Soft Skills, Ferramentas)
    CREATE TABLE TB_SKILL_HABILIDADE (
        id_habilidade           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nm_habilidade           VARCHAR2(100) NOT NULL UNIQUE,
        ds_categoria_habilidade VARCHAR2(50)  NOT NULL CHECK (ds_categoria_habilidade IN ('HARD_SKILL', 'SOFT_SKILL', 'FERRAMENTA'))
    );

    -- Tabela de Usuários / Trabalhadores
    CREATE TABLE TB_SKILL_USUARIO (
        id_usuario              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nm_usuario              VARCHAR2(100) NOT NULL,
        ds_email                VARCHAR2(100) NOT NULL UNIQUE,
        ds_senha                VARCHAR2(255) NOT NULL,
        ds_titulo_cargo         VARCHAR2(100)
    );

    -- Tabela de Vagas de Emprego
    CREATE TABLE TB_SKILL_VAGA (
        id_vaga                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nm_empresa              VARCHAR2(100) NOT NULL,
        ds_titulo_vaga          VARCHAR2(100) NOT NULL,
        ds_descricao_vaga       CLOB
    );

    -- === 2. TABELAS PIVOT (Relacionamentos Many-to-Many) ===

    -- Tabela que liga quais HABILIDADES um USUARIO POSSUI
    CREATE TABLE TB_SKILL_USUARIO_HABILIDADE (
        id_usuario_habilidade   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_usuario              NUMBER NOT NULL,
        id_habilidade           NUMBER NOT NULL,
        CONSTRAINT fk_usuario_hab_usu FOREIGN KEY (id_usuario) REFERENCES TB_SKILL_USUARIO(id_usuario) ON DELETE CASCADE,
        CONSTRAINT fk_usuario_hab_hab FOREIGN KEY (id_habilidade) REFERENCES TB_SKILL_HABILIDADE(id_habilidade) ON DELETE CASCADE,
        CONSTRAINT uk_usuario_habilidade UNIQUE (id_usuario, id_habilidade)
    );

    -- Tabela que liga quais HABILIDADES uma VAGA REQUER
    CREATE TABLE TB_SKILL_VAGA_HABILIDADE (
        id_vaga_habilidade      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_vaga                 NUMBER NOT NULL,
        id_habilidade           NUMBER NOT NULL,
        nr_nivel_exigido        NUMBER(1) DEFAULT 1 NOT NULL,
        CONSTRAINT fk_vaga_hab_vaga FOREIGN KEY (id_vaga) REFERENCES TB_SKILL_VAGA(id_vaga) ON DELETE CASCADE,
        CONSTRAINT fk_vaga_hab_hab FOREIGN KEY (id_habilidade) REFERENCES TB_SKILL_HABILIDADE(id_habilidade) ON DELETE CASCADE,
        CONSTRAINT uk_vaga_habilidade UNIQUE (id_vaga, id_habilidade)
    );

    -- === 3. DADOS INICIAIS (Para Testes de CRUD) ===
    -- Habilidades
    INSERT INTO TB_SKILL_HABILIDADE (nm_habilidade, ds_categoria_habilidade) VALUES ('Java 17', 'HARD_SKILL');
    INSERT INTO TB_SKILL_HABILIDADE (nm_habilidade, ds_categoria_habilidade) VALUES ('Spring Boot', 'HARD_SKILL');
    INSERT INTO TB_SKILL_HABILIDADE (nm_habilidade, ds_categoria_habilidade) VALUES ('Oracle PL/SQL', 'HARD_SKILL');
    INSERT INTO TB_SKILL_HABILIDADE (nm_habilidade, ds_categoria_habilidade) VALUES ('MongoDB', 'FERRAMENTA');
    INSERT INTO TB_SKILL_HABILIDADE (nm_habilidade, ds_categoria_habilidade) VALUES ('Azure DevOps', 'FERRAMENTA');

    -- Usuários
    INSERT INTO TB_SKILL_USUARIO (nm_usuario, ds_email, ds_senha, ds_titulo_cargo) VALUES ('Ana Silva', 'ana@email.com', '$2a$10$fP8.sS9.G8kFzUbGf/3Yy.AC4.M8Qe.QhJ2d.QZ.bYv1.X7n.X7mK', 'Desenvolvedora Backend Jr');
    INSERT INTO TB_SKILL_USUARIO (nm_usuario, ds_email, ds_senha, ds_titulo_cargo) VALUES ('Carla Dias', 'carla@email.com', '$2a$10$fP8.sS9.G8kFzUbGf/3Yy.AC4.M8Qe.QhJ2d.QZ.bYv1.X7n.X7mK', 'Engenheira DevOps');

    -- Vagas
    INSERT INTO TB_SKILL_VAGA (nm_empresa, ds_titulo_vaga, ds_descricao_vaga) VALUES ('Empresa A', 'Vaga Desenvolvedor Backend Pleno (Java)', 'Buscamos dev Java/Spring para atuar em projetos de IA...');
    INSERT INTO TB_SKILL_VAGA (nm_empresa, ds_titulo_vaga, ds_descricao_vaga) VALUES ('Empresa C', 'Vaga SRE/DevOps Pleno', 'Vaga para DevOps com experiência em Cloud (Azure) e CI/CD...');

    -- Habilidades que a 'Ana' (ID 1) POSSUI
    INSERT INTO TB_SKILL_USUARIO_HABILIDADE (id_usuario, id_habilidade) VALUES (1, 1); -- Java 17
    INSERT INTO TB_SKILL_USUARIO_HABILIDADE (id_usuario, id_habilidade) VALUES (1, 2); -- Spring Boot

    -- Habilidades que a 'Carla' (ID 2) POSSUI
    INSERT INTO TB_SKILL_USUARIO_HABILIDADE (id_usuario, id_habilidade) VALUES (2, 5); -- Azure DevOps

    -- Habilidades que a 'Vaga Backend' (ID 1) REQUER
    INSERT INTO TB_SKILL_VAGA_HABILIDADE (id_vaga, id_habilidade, nr_nivel_exigido) VALUES (1, 1, 3); -- Java 17
    INSERT INTO TB_SKILL_VAGA_HABILIDADE (id_vaga, id_habilidade, nr_nivel_exigido) VALUES (1, 2, 3); -- Spring Boot
    INSERT INTO TB_SKILL_VAGA_HABILIDADE (id_vaga, id_habilidade, nr_nivel_exigido) VALUES (1, 3, 2); -- Oracle PL/SQL

    -- Habilidades que a 'Vaga DevOps' (ID 2) REQUER
    INSERT INTO TB_SKILL_VAGA_HABILIDADE (id_vaga, id_habilidade, nr_nivel_exigido) VALUES (2, 5, 4); -- Azure DevOps

    COMMIT;

    /

    EXIT;